version: '3.8'
services:
  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - spring-net
    depends_on:
      - database

  database:
    container_name: database
    image: mysql:8.0
    restart: always
    networks:
      - spring-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crs_database
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - '3306:3306'
    volumes:
      - dbstore:/var/lib/mysql

volumes:
  dbstore:

networks:
  spring-net: